export const CLOSE_DIALOG = 'CLOSE_DIALOG';
export const OPEN_WALLET_DIALOG = 'OPEN_WALLET_DIALOG';
export const OPEN_SETTINGS_DIALOG = 'OPEN_SETTINGS_DIALOG';
export const OPEN_LOGS_DIALOG = 'OPEN_LOGS_DIALOG';
export const OPEN_SUPPORT_DIALOG = 'OPEN_SUPPORT_DIALOG';
export const SET_SETTINGS_DIALOG_TAB = 'SET_SETTINGS_DIALOG_TAB';
export const SET_SUPPORT_DIALOG_TAB = 'SET_SUPPORT_DIALOG_TAB';
