export const CLOSE_DIALOG = 'CLOSE_DIALOG';
export const OPEN_CRYPTO_DIALOG = 'OPEN_CRYPTO_DIALOG';
export const OPEN_SETTINGS_DIALOG = 'OPEN_SETTINGS_DIALOG';
export const OPEN_STATS_DIALOG = 'OPEN_STATS_DIALOG';
export const OPEN_SUPPORT_DIALOG = 'OPEN_SUPPORT_DIALOG';
