export { default as AssessmentIcon } from '@material-ui/icons/Assessment';
export { default as CloseIcon } from '@material-ui/icons/Close';
export { default as DoneIcon } from '@material-ui/icons/Done';
export { default as ErrorIcon } from '@material-ui/icons/Error';
export { default as HelpIcon } from '@material-ui/icons/Help';
export { default as SettingsIcon } from '@material-ui/icons/Settings';
export { default as AddIcon } from '@material-ui/icons/Add';
export { default as RemoveIcon } from '@material-ui/icons/Remove';
export { default as WalletIcon } from '@material-ui/icons/AccountBalanceWallet';
