import { CRYPTO_NIGHT_HEAVY, CRYPTO_NIGHT_V7 } from '../mining';

export const ALGORITHMS = {
  [CRYPTO_NIGHT_V7]: 30,
  [CRYPTO_NIGHT_HEAVY]: 31
};

export const ALGORITHMS_BY_ID = {
  30: CRYPTO_NIGHT_V7,
  31: CRYPTO_NIGHT_HEAVY
};
